name: Jekyll Build

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name:
      run: |-
        mkdir -p _zip
        echo; echo "Folders created:"
        ls
        echo; echo "Moving to _site Folder:"
        cd _site
        ls
        echo; echo "Creating zip:"
        zip -r -v ../_zip/devops.zip *
